name: Feature Request
description: Suggest a new feature or enhancement for the project
title: "[Feature Request]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to open a feature request! Please provide us with the following information:

  - type: input
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you are requesting.
      placeholder: "Add a short summary of the feature"

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A detailed description of the feature you are requesting.
      placeholder: "Describe the feature in detail"

  - type: input
    id: use-case
    attributes:
      label: Use Case
      description: Describe the use case for this feature.
      placeholder: "Explain how this feature will be used"

  - type: input
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any alternative solutions or features you've considered.
      placeholder: "List any alternatives you've considered"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: "Add any other context or screenshots"